const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const { Workbook } = require('exceljs');
const { launch } = require('./helpers.cjs');

test('表格预览：真实打包解析、工作表键盘切换、类型与未重算公式，外部变化保留旧视图', { timeout: 60000 }, async t => {
  const { app, page, data } = await launch(); t.after(() => app.close());
  const filename = path.join(data, '季度经营.xlsx'), book = new Workbook();
  const detail = book.addWorksheet('明细'); detail.addRow(['月份', '收入', '支出', '编号']);
  detail.addRow(['一月', 120000, 80000, '0012']);
  book.addWorksheet('汇总').getCell('A1').value = { formula: "'明细'!B2-'明细'!C2", result: 40000 };
  await fs.writeFile(filename, Buffer.from(await book.xlsx.writeBuffer()));
  await app.evaluate(({ dialog }, filename) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [filename] }); }, filename);
  await page.getByRole('button', { name: '添加材料', exact: true }).click();
  await page.getByRole('menuitem', { name: '添加文件', exact: true }).click();
  await page.getByRole('status').filter({ hasText: '草稿已保存' }).waitFor();
  await page.getByRole('button', { name: '预览材料：季度经营.xlsx' }).click();
  const preview = page.getByRole('region', { name: '只读文件预览' });
  await preview.getByRole('table', { name: '明细' }).waitFor();
  assert.equal(await preview.getByRole('cell', { name: '0012', exact: true }).count(), 1);
  const tabs = preview.getByRole('tablist', { name: '工作表' });
  await tabs.getByRole('tab', { name: '明细', exact: true }).focus();
  await page.keyboard.press('ArrowRight');
  await preview.getByRole('table', { name: '汇总' }).waitFor();
  assert.equal(await tabs.getByRole('tab', { name: '汇总', exact: true }).evaluate(element => element === document.activeElement), true);
  await preview.getByRole('cell', { name: /40000/ }).click();
  await preview.getByText("='明细'!B2-'明细'!C2", { exact: true }).waitFor();
  await preview.getByRole('note').filter({ hasText: '公式未重算' }).waitFor();
  await fs.writeFile(filename, Buffer.from('损坏的外部新版本'));
  await preview.getByRole('button', { name: '重新核验预览' }).click();
  await preview.getByRole('alert').waitFor();
  assert.equal(await preview.getByRole('table', { name: '汇总' }).count(), 1);
  await preview.getByRole('note').filter({ hasText: '保留上次成功读取' }).waitFor();
  await preview.getByRole('button', { name: '关闭文件预览' }).press('Escape');
  assert.equal(await page.getByRole('button', { name: '预览材料：季度经营.xlsx' }).evaluate(element => element === document.activeElement), true);
});

test('表格草稿重开：材料与原版本恢复，损坏表格明确失败而非空表', { timeout: 60000 }, async t => {
  let desktop = await launch();
  t.after(async () => { if (desktop) await desktop.app.close(); });
  const { app, page, data } = desktop, filename = path.join(data, '保留编号.csv'), broken = path.join(data, '损坏.xlsx');
  await fs.writeFile(filename, '名称,编号\n青禾,0012'); await fs.writeFile(broken, 'not-a-workbook');
  await app.evaluate(({ dialog }, files) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: files }); }, [filename, broken]);
  await page.getByRole('button', { name: '添加材料', exact: true }).click(); await page.getByRole('menuitem', { name: '添加文件', exact: true }).click();
  await page.getByRole('button', { name: '预览材料：损坏.xlsx' }).waitFor();
  await page.waitForFunction(async () => (await window.agentx.getDraft({ projectId: null, taskId: null })).materials.length === 2);
  await page.getByRole('status').filter({ hasText: '草稿已保存' }).waitFor();
  const saved = await page.evaluate(() => window.agentx.getDraft({ projectId: null, taskId: null }));
  assert.equal(saved.materials.length, 2);
  assert.equal(saved.materials[1].status, 'unreadable');
  await app.close(); desktop = undefined;
  desktop = await launch(data);
  await desktop.page.getByRole('button', { name: '预览材料：保留编号.csv' }).click();
  const preview = desktop.page.getByRole('region', { name: '只读文件预览' });
  await preview.getByRole('cell', { name: '0012', exact: true }).waitFor();
  assert.deepEqual((await desktop.page.evaluate(() => window.agentx.getDraft({ projectId: null, taskId: null }))).materials, saved.materials);
  await desktop.page.getByRole('button', { name: '预览材料：损坏.xlsx' }).click();
  await preview.getByRole('alert').waitFor(); assert.equal(await preview.getByRole('table').count(), 0);
  assert.equal(await fs.readFile(filename, 'utf8'), '名称,编号\n青禾,0012');
});
